import React from 'react';
import {
  VerifiedUser,
  Gesture,
  Merge,
  CallSplit,
  Compress,
  Image as ImageIcon,
  Description,
  TableChart,
  Code,
  Edit,
  Folder,
  Transform,
  Analytics,
  CompareArrows,
  RotateRight,
} from '@mui/icons-material';

export const featureCategories = [
  {
    id: 'edit',
    titleKey: 'menuGroups.edit',
    defaultTitle: 'PDF编辑',
    icon: <Edit sx={{ fontSize: 24 }} />,
    color: 'primary',
    descriptionKey: 'menuGroups.editDescription',
    defaultDescription: '编辑PDF文档内容、添加印章和签名',
  },
  {
    id: 'organize',
    titleKey: 'menuGroups.organize',
    defaultTitle: 'PDF组织',
    icon: <Folder sx={{ fontSize: 24 }} />,
    color: 'success',
    descriptionKey: 'menuGroups.organizeDescription',
    defaultDescription: '合并、拆分、压缩PDF文件',
  },
  {
    id: 'convert',
    titleKey: 'menuGroups.convert',
    defaultTitle: '格式转换',
    icon: <Transform sx={{ fontSize: 24 }} />,
    color: 'warning',
    descriptionKey: 'menuGroups.convertDescription',
    defaultDescription: 'PDF与其他格式互转',
  },
  {
    id: 'analyze',
    titleKey: 'menuGroups.analyze',
    defaultTitle: 'PDF分析',
    icon: <Analytics sx={{ fontSize: 24 }} />,
    color: 'info',
    descriptionKey: 'menuGroups.analyzeDescription',
    defaultDescription: '比较、提取、优化PDF',
  },
];

export const features = [
  // PDF编辑类
  {
    id: 'rotate',
    titleKey: 'home.features.rotate.title',
    descriptionKey: 'home.features.rotate.description',
    icon: <RotateRight sx={{ fontSize: 40 }} />,
    path: '/rotate',
    processingType: 'local',
    category: 'organize',
    showInHeader: true,
  },
  {
    id: 'stamp',
    titleKey: 'home.features.stamp.title',
    descriptionKey: 'home.features.stamp.description',
    icon: <VerifiedUser sx={{ fontSize: 40 }} />,
    path: '/stamp',
    processingType: 'local',
    category: 'edit',
    showInHeader: true,
  },
  {
    id: 'sign',
    titleKey: 'home.features.sign.title',
    descriptionKey: 'home.features.sign.description',
    icon: <Gesture sx={{ fontSize: 40 }} />,
    path: '/sign',
    processingType: 'local',
    category: 'edit',
    showInHeader: true,
  },
  // PDF组织类
  {
    id: 'merge',
    titleKey: 'home.features.merge.title',
    descriptionKey: 'home.features.merge.description',
    icon: <Merge sx={{ fontSize: 40 }} />,
    path: '/merge',
    processingType: 'local',
    category: 'organize',
    showInHeader: true,
  },
  {
    id: 'split',
    titleKey: 'home.features.split.title',
    descriptionKey: 'home.features.split.description',
    icon: <CallSplit sx={{ fontSize: 40 }} />,
    path: '/split',
    processingType: 'local',
    category: 'organize',
    showInHeader: true,
  },
  {
    id: 'compress',
    titleKey: 'home.features.compress.title',
    descriptionKey: 'home.features.compress.description',
    icon: <Compress sx={{ fontSize: 40 }} />,
    path: '/compress',
    processingType: 'local',
    category: 'organize',
    showInHeader: true,
  },
  // 格式转换类
  {
    id: 'pdfToWord',
    titleKey: 'home.features.pdfToWord.title',
    descriptionKey: 'home.features.pdfToWord.description',
    icon: <Description sx={{ fontSize: 40 }} />,
    path: '/pdf-to-word',
    processingType: 'server',
    category: 'convert',
    showInHeader: true,
  },
  {
    id: 'pdfToExcel',
    titleKey: 'home.features.pdfToExcel.title',
    descriptionKey: 'home.features.pdfToExcel.description',
    icon: <TableChart sx={{ fontSize: 40 }} />,
    path: '/pdf-to-excel',
    processingType: 'server',
    category: 'convert',
    showInHeader: true,
  },
  {
    id: 'imageToPdf',
    titleKey: 'home.features.imageToPdf.title',
    descriptionKey: 'home.features.imageToPdf.description',
    icon: <ImageIcon sx={{ fontSize: 40 }} />,
    path: '/image-to-pdf',
    processingType: 'local',
    category: 'convert',
    showInHeader: true,
  },
  {
    id: 'pdfToImage',
    titleKey: 'home.features.pdfToImage.title',
    descriptionKey: 'home.features.pdfToImage.description',
    icon: <ImageIcon sx={{ fontSize: 40 }} />,
    path: '/pdf-to-image',
    processingType: 'local',
    category: 'convert',
    showInHeader: true,
  },
  {
    id: 'documentToMarkdown',
    titleKey: 'home.features.documentToMarkdown.title',
    descriptionKey: 'home.features.documentToMarkdown.description',
    icon: <Code sx={{ fontSize: 40 }} />,
    path: '/document-to-markdown',
    processingType: 'server',
    category: 'convert',
    showInHeader: true,
  },
  // PDF分析类
  {
    id: 'extract',
    titleKey: 'home.features.extract.title',
    descriptionKey: 'home.features.extract.description',
    icon: <ImageIcon sx={{ fontSize: 40 }} />, // Consider a different icon if clashing with ImageToPdf/PdfToImage
    path: '/extract',
    processingType: 'local',
    category: 'analyze',
    showInHeader: true,
  },
  {
    id: 'pdfCompare',
    titleKey: 'home.features.pdfCompare.title',
    descriptionKey: 'home.features.pdfCompare.description',
    icon: <CompareArrows sx={{ fontSize: 40 }} />,
    path: '/pdf-compare',
    processingType: 'local',
    category: 'analyze',
    showInHeader: true,
  },
]; 